name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Cleanup
      #   run: yarn clean
      - name: Installing dependencies
        run: |
          yarn install
      # - name: Running tests
      #   run: |
      #     yarn test
      - name: Build
        run: |
          yarn build
      - name: Updating package version
        run: |
          npm version patch
      - name: Publishing package
        run: |
          npm publish
