name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - name: Cleanup
      #   run: yarn clean
      - name: Installing dependencies
        run: |
          yarn install
      # - name: Running tests
      #   run: |
      #     yarn test
      - name: Build
        run: |
          yarn build
