name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      # - name: Cleanup
      #   run: yarn clean
      - name: Installing dependencies
        # echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        run: |
          yarn install
      # - name: Running tests
      #   run: |
      #     yarn test
      - name: Build
        run: |
          yarn build
      - name: Setup Git
        # git fetch
        # git pull
        run: |
          git stash
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Bumping version
        run: |
          npm version patch
      - name: Publishing
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PACKAGE_NEXT_VERSION: npm info lena-melo-design-tokens version
        # git add .
        # git commit -am "Publishing version $PACKAGE_NEXT_VERSION"
        run: |
          echo PACKAGE_NEXT_VERSION
          npm publish --tag=next
          git push origin --all
          git push origin --tags
