name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Installing dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Setup Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git stash
      - name: Bumping version
        run: |
          npm version patch
      - name: Publishing
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PACKAGE_NEXT_VERSION: npm info lena-melo-design-tokens version
        run: |
          echo PACKAGE_NEXT_VERSION
          npm publish --tag=next
          git push origin --all
          git push origin --tags
